# Generated by Django 3.2.5 on 2021-07-26 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('url_logo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.BigIntegerField()),
                ('tipo_identification', models.CharField(choices=[('CC', 'Cedula'), ('CE', 'Cedula Extranjeria'), ('PP', 'Pasaporte')], default='CC', max_length=2)),
                ('fecha_expedicion', models.DateField(null=True)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ObligacionFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_referencia', models.CharField(max_length=100)),
                ('estado_obligacion', models.CharField(max_length=150)),
                ('fecha_ultimo_pago', models.DateField(null=True)),
                ('dias_mora', models.IntegerField()),
                ('saldo_vencido', models.FloatField()),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartera.clientes')),
                ('persona_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartera.persona')),
            ],
        ),
    ]
