# Generated by Django 4.0.1 on 2022-01-20 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('url_logo', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='ObligacionFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_referencia', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartera.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Obligacion Financiera',
                'verbose_name_plural': 'Obligaciones Financieras',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.BigIntegerField()),
                ('tipo_identification', models.CharField(default='CC', max_length=2)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('codigo_ref', models.CharField(max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recaudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_obligacion', models.CharField(max_length=150)),
                ('fecha_pago_recaudo', models.DateField(null=True)),
                ('tramo', models.CharField(max_length=150)),
                ('valor_recaudo', models.FloatField()),
                ('obligacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartera.obligacionfinanciera', verbose_name='Obligacion')),
            ],
        ),
        migrations.AddField(
            model_name='obligacionfinanciera',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartera.persona', verbose_name='Deudor'),
        ),
        migrations.CreateModel(
            name='CuentasPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_obligacion', models.CharField(max_length=150)),
                ('fecha_ultimo_pago', models.DateField()),
                ('tramo', models.CharField(max_length=150)),
                ('dias_mora', models.IntegerField()),
                ('saldo_vencido', models.FloatField(verbose_name='Saldo en Mora')),
                ('total_pagar', models.FloatField(verbose_name='Total a Pagar')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('obligacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartera.obligacionfinanciera', verbose_name='Obligacion')),
            ],
            options={
                'verbose_name': 'Cuenta por cobrar',
                'verbose_name_plural': 'Cuentas por Cobrar',
            },
        ),
        migrations.CreateModel(
            name='AcuerdoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuotas', models.IntegerField()),
                ('fecha_compromiso', models.DateField()),
                ('valor_cuota', models.FloatField()),
                ('comentarios', models.CharField(max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('obligacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartera.obligacionfinanciera', verbose_name='Obligacion')),
            ],
        ),
    ]
