# Generated by Django 3.2.5 on 2022-02-12 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('url_logo', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.IntegerField(unique=True)),
                ('tipo_identification', models.CharField(default='CC', max_length=2)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObligacionFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_referencia', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartera.cliente', verbose_name='Cliente')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartera.persona', verbose_name='Deudor')),
            ],
            options={
                'verbose_name': 'Obligacion Financiera',
                'verbose_name_plural': 'Obligaciones Financieras',
            },
        ),
        migrations.CreateModel(
            name='EstudioCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_solicitado', models.FloatField(default=0)),
                ('cuotas', models.IntegerField(default=0)),
                ('documento_adjunto', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('RADICADO', 'RADICADO'), ('EN_ESTUDIO', 'EN ESTUDIO'), ('PREAPROBADO', 'PREAPROBADO'), ('APROBADO', 'APROBADO'), ('DENEGADO', 'DENEGADO'), ('FALTA_INFORMACION', 'FALTA INFORMACION')], default='EN_ESTUDIO', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartera.persona')),
            ],
            options={
                'verbose_name': 'Estudio De Credito',
                'verbose_name_plural': 'Estudios de Credito',
            },
        ),
        migrations.CreateModel(
            name='CuentasPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=100)),
                ('estado_obligacion', models.CharField(max_length=150)),
                ('fecha_ultimo_pago', models.DateTimeField(blank=True, null=True)),
                ('fecha_limite_pago', models.DateTimeField()),
                ('tramo', models.CharField(max_length=150)),
                ('dias_mora', models.IntegerField(blank=True, null=True)),
                ('saldo_vencido', models.FloatField(verbose_name='Saldo en Mora')),
                ('total_pagar', models.FloatField(verbose_name='Total a Pagar')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('obligacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartera.obligacionfinanciera', verbose_name='Obligacion')),
            ],
            options={
                'verbose_name': 'Cuenta por cobrar',
                'verbose_name_plural': 'Cuentas por Cobrar',
            },
        ),
        migrations.CreateModel(
            name='AcuerdoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuotas', models.IntegerField()),
                ('fecha_compromiso', models.DateField()),
                ('valor_cuota', models.FloatField()),
                ('estado', models.BooleanField(default=False)),
                ('comentarios', models.CharField(max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('obligacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartera.obligacionfinanciera', verbose_name='Obligacion')),
            ],
        ),
    ]
