# Generated by Django 3.2.5 on 2021-07-26 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='obligacionfinanciera',
            options={'verbose_name': 'Obligacion Financiera', 'verbose_name_plural': 'Obligaciones Financieras'},
        ),
        migrations.AlterField(
            model_name='obligacionfinanciera',
            name='cliente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartera.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='obligacionfinanciera',
            name='persona_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartera.persona', verbose_name='Deudor'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_expedicion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
