# Generated by Django 4.0.1 on 2022-01-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acuerdopago',
            name='fecha_compromiso',
            field=models.DateField(blank=True),
        ),
    ]
