# Generated by Django 3.2.5 on 2022-01-29 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='nombre',
            new_name='nombre_completo',
        ),
        migrations.DeleteModel(
            name='Recaudo',
        ),
    ]
