# Generated by Django 3.2.5 on 2021-07-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0002_auto_20210726_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obligacionfinanciera',
            old_name='cliente_id',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='obligacionfinanciera',
            old_name='persona_id',
            new_name='persona',
        ),
    ]
