# Generated by Django 3.2.5 on 2022-01-29 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0002_auto_20220129_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudioCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_solicitado', models.FloatField(default=0)),
                ('cuotas', models.IntegerField(default=0)),
                ('documento_adjunto', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('EN_ESTUDIO', 'EN ESTUDIO'), ('PREAPROBADO', 'PREAPROBADO'), ('APROBADO', 'APROBADO'), ('DENEGADO', 'DENEGADO'), ('FALTA_INFORMACION', 'FALTA INFORMACION')], default='EN_ESTUDIO', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartera.persona')),
            ],
            options={
                'verbose_name': 'Estudio De Credito',
                'verbose_name_plural': 'Estudios de Credito',
            },
        ),
    ]
