# Generated by Django 3.2.5 on 2021-07-26 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0003_auto_20210726_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='obligacionfinanciera',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='obligacionfinanciera',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obligacionfinanciera',
            name='total_pagar',
            field=models.FloatField(default=0, verbose_name='Total a Pagar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 7, 26, 17, 30, 38, 882099, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='obligacionfinanciera',
            name='saldo_vencido',
            field=models.FloatField(verbose_name='Saldo en Mora'),
        ),
    ]
