# Generated by Django 3.2.5 on 2021-07-27 22:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0004_auto_20210726_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obligacionfinanciera',
            name='actualizado',
        ),
        migrations.RemoveField(
            model_name='obligacionfinanciera',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='obligacionfinanciera',
            name='dias_mora',
        ),
        migrations.RemoveField(
            model_name='obligacionfinanciera',
            name='estado_obligacion',
        ),
        migrations.RemoveField(
            model_name='obligacionfinanciera',
            name='fecha_ultimo_pago',
        ),
        migrations.RemoveField(
            model_name='obligacionfinanciera',
            name='saldo_vencido',
        ),
        migrations.RemoveField(
            model_name='obligacionfinanciera',
            name='total_pagar',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='nombre_completo',
        ),
        migrations.AddField(
            model_name='persona',
            name='primer_apellido',
            field=models.CharField(default=datetime.datetime(2021, 7, 27, 22, 27, 27, 319228, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='primer_nombre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='segundo_apellido',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='segundo_nombre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Recaudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_obligacion', models.CharField(max_length=150)),
                ('fecha_pago_recaudo', models.DateField(null=True)),
                ('tramo', models.CharField(max_length=150)),
                ('valor_recaudo', models.FloatField()),
                ('obligacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartera.obligacionfinanciera', verbose_name='Obligacion')),
            ],
        ),
        migrations.CreateModel(
            name='CuentasPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=100)),
                ('estado_obligacion', models.CharField(max_length=150)),
                ('fecha_ultimo_pago', models.DateField(null=True)),
                ('tramo', models.CharField(max_length=150)),
                ('dias_mora', models.IntegerField()),
                ('saldo_vencido', models.FloatField(verbose_name='Saldo en Mora')),
                ('total_pagar', models.FloatField(verbose_name='Total a Pagar')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('obligacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartera.obligacionfinanciera', verbose_name='Obligacion')),
            ],
        ),
        migrations.CreateModel(
            name='AcuerdoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuotas', models.IntegerField()),
                ('valor_cuota', models.FloatField()),
                ('comentarios', models.CharField(max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('obligacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartera.obligacionfinanciera', verbose_name='Obligacion')),
            ],
        ),
    ]
