# Generated by Django 3.2.5 on 2021-12-16 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0006_auto_20210730_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuentasporcobrar',
            options={'verbose_name': 'Cuenta por cobrar', 'verbose_name_plural': 'Cuentas por Cobrar'},
        ),
        migrations.AddField(
            model_name='acuerdopago',
            name='fecha_compromiso',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
