# Generated by Django 3.2.5 on 2021-12-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0007_auto_20211216_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acuerdopago',
            name='fecha_compromiso',
            field=models.DateField(),
        ),
    ]
